import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "@/providers";

import { Header } from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Sign In | AI4US",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" data-theme="light">
      <Providers>
        <body className="antialiased">
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
