import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sign In | AI4US",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" data-theme="light">
      <body className="antialiased">{children}</body>
    </html>
  );
}
